# Generated by Django 3.1.1 on 2020-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20200915_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=' ', max_length=14),
            preserve_default=False,
        ),
    ]
